# wagonOS ly display manager config
# Reference: /etc/ly/config.ini.example

animation = matrix
hide_borders = false
asterisk = *
bg = 0x000000
fg = 0xFFFFFF
border_fg = 0x4287F5
default_input = login
input_len = 34
margin_box_h = 2
margin_box_v = 1
clock = %F %R
load = true
save = true
